CRITICAL - 2020-03-23 18:34:41 --> Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2206): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bs...', Array, false)
#3 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#5 C:\xampp-newer\htdocs\bitmoser\app\Controllers\API\API_Authentication.php(84): CodeIgniter\Model->save(Object(App\Entities\AuthCreateServiator))
#6 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\API\API_Authentication->bs_api_create_serviator()
#7 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\API_Authentication))
#8 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp-newer\htdocs\bitmoser\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2020-03-23 18:34:53 --> Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2206): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bs...', Array, false)
#3 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#5 C:\xampp-newer\htdocs\bitmoser\app\Controllers\API\API_Authentication.php(84): CodeIgniter\Model->save(Object(App\Entities\AuthCreateServiator))
#6 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\API\API_Authentication->bs_api_create_serviator()
#7 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\API_Authentication))
#8 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp-newer\htdocs\bitmoser\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2020-03-23 18:35:13 --> Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2206): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bs...', Array, false)
#3 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#5 C:\xampp-newer\htdocs\bitmoser\app\Controllers\API\API_Authentication.php(84): CodeIgniter\Model->save(Object(App\Entities\AuthCreateServiator))
#6 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\API\API_Authentication->bs_api_create_serviator()
#7 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\API_Authentication))
#8 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp-newer\htdocs\bitmoser\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2020-03-23 18:37:33 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(330): mysqli->query('INSERT INTO `bs...')
#1 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bs...')
#2 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bs...')
#3 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2206): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bs...', Array, false)
#4 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp-newer\htdocs\bitmoser\app\Controllers\API\API_Authentication.php(84): CodeIgniter\Model->save(Object(App\Entities\AuthCreateServiator))
#7 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\API\API_Authentication->bs_api_create_serviator()
#8 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\API_Authentication))
#9 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp-newer\htdocs\bitmoser\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2020-03-23 18:43:27 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(330): mysqli->query('INSERT INTO `bs...')
#1 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bs...')
#2 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bs...')
#3 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2206): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bs...', Array, false)
#4 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp-newer\htdocs\bitmoser\app\Controllers\API\API_Authentication.php(84): CodeIgniter\Model->save(Object(App\Entities\AuthCreateServiator))
#7 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\API\API_Authentication->bs_api_create_serviator()
#8 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\API_Authentication))
#9 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp-newer\htdocs\bitmoser\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2020-03-23 18:44:57 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(330): mysqli->query('INSERT INTO `bs...')
#1 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bs...')
#2 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bs...')
#3 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2206): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bs...', Array, false)
#4 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp-newer\htdocs\bitmoser\app\Controllers\API\API_Authentication.php(84): CodeIgniter\Model->save(Object(App\Entities\AuthCreateServiator))
#7 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\API\API_Authentication->bs_api_create_serviator()
#8 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\API_Authentication))
#9 C:\xampp-newer\htdocs\bitmoser\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp-newer\htdocs\bitmoser\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
